### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False on Linux

### ISSUE THREAD

**Issue by arn13** [macaodha/batdetect#11]
Hi,
I have an issue which might be related to [this one](https://github.com/macaodha/batdetect/issues/10), but the fix for that one did not work for me. I am also running Linux Mint and not Windows. I tried to use python 2.7.18 , python 3.8.10 and python 3.9.6.
My requirement versions are: 
`Cython          0.29.24
numpy           1.16.6
pandas          0.24.2
scipy           1.2.3`
All of them installed via pip

The first error:
```
python run_detector.py
Import Error: No module named nms
please compile fast nms by running:
python setup.py build_ext --inplace
using slow nms in the meantime.
Processing         1 files
Input directory    wavs
Results directory  results 

Traceback (most recent call last):
  File "run_detector.py", line 115, in <module>
    det = detector.CPUDetector(det_model_file, det_params_file)
  File "/home/arn/bats/batdetect/bat_eval/cpu_detection.py", line 36, in __init__
    self.weights = np.load(weight_file, encoding='latin1')
  File "/home/arn/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/arn/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

When I try to compile fast non maximum suppression:
```
python setup.py build_ext --inplace
Compiling nms.pyx because it changed.
[1/1] Cythonizing nms.pyx
/home/arn/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/arn/bats/batdetect/bat_eval/nms.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'nms' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QDqKfA/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/arn/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c nms.c -o build/temp.linux-x86_64-2.7/nms.o -fopenmp -ffast-math -msse -msse2 -msse3 -msse4 -s -std=c99
In file included from /home/arn/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
                 from /home/arn/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/arn/.local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from nms.c:646:
/home/arn/.local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QDqKfA/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-QDqKfA/python2.7-2.7.18=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC build/temp.linux-x86_64-2.7/nms.o -o /home/arn/bats/batdetect/bat_eval/nms.so -fopenmp`
```

The error basically remains the same afterwards:

```
python run_detector.py
Processing         1 files
Input directory    wavs
Results directory  results 

Traceback (most recent call last):
  File "run_detector.py", line 115, in <module>
    det = detector.CPUDetector(det_model_file, det_params_file)
  File "/home/arn/bats/batdetect/bat_eval/cpu_detection.py", line 36, in __init__
    self.weights = np.load(weight_file, encoding='latin1')
  File "/home/arn/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/arn/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

The "results" and "individual_results" folders are created but remain empty.
I have a feeling that this might be a beginner problem, which will hopefully make it easy to resolve for someone who knows what they are doing.

**Comment by macaodha** [comment]
Hi there. 

I haven't tested the code using the package versions you are using. If you have not already done so, try with the versions specified here:
https://github.com/macaodha/batdetect/tree/master/bat_eval#requirements

Hope this helps,
Oisin

**Comment by arn13** [comment]
I manged to downgrade the requirements to these versions:
`Cython          0.24.1
numpy           1.16.6
pandas          0.24.2
scipy           0.19.0
`
run_detector.py does seem to work with these versions.
specifying the data directory via option does not seem to work as does the `save_individual_results = False`
But this is a minor problem since setting those in the file does work.

Thank you for your quick support.

**Comment by macaodha** [comment]
Great, glad you got it working. In general the codebase, is old and we plan on having something new available in the next few months.
